apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: demo
spec:
  selector:
    app: node-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 31123